package application;

import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;

import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.input.MouseEvent;

public class ModifierActualiteController implements Initializable
{
	int mx=0;
	   @FXML
	    private Label vld;
	@FXML
	private ComboBox<String>  box;

    @FXML
    private TextArea newAct;

	// Event Listener on Label.onMouseClicked
	@FXML
	public void modifier(MouseEvent event) throws SQLException {
		// TODO Autogenerated
		Connection con =Connexion.connectDb();
		PreparedStatement ps=con.prepareStatement("update actualite set text=? where titre=?");
		ps.setString(1,newAct.getText());
		ps.setString(2, box.getValue());
		if(!ps.execute())
		{
			vld.setVisible(true);
		}
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		Connection con =Connexion.connectDb();
		try {
			
			PreparedStatement ps=con.prepareStatement("select max(idA) from actualite");
		ResultSet rsl=	ps.executeQuery();
		if (rsl.next())
		{
			mx=rsl.getInt(1);
		}
		 String [] items=new String[mx];
		 PreparedStatement ps2=con.prepareStatement("select titre from actualite");
			ResultSet rsl2=	ps2.executeQuery();
		 int i=0;
			while(rsl2.next())
			{
				items[i]=rsl2.getString(1);
				i++;
			}
			box.getItems().addAll(items);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
}
